# Site settings
author: KP
title: Stories of the late night programmer
header-img: img/home-bg.png
email: pediadk@gmail.com
copyright_name: KP
description: > # this means to ignore newlines until "baseurl:"
  A collection of short horror stories in the realm of coding... 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kpediad

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
